SRC=src
BIN=bin
OPTIONS=-Wall -g
LIBS=-lSDL2

TARGET_VIS = visual
OBJ_VIS = testApp.o App.o Script.o Common.o
OBJ_SRC = testApp.cpp App.cpp Script.cpp Common.cpp

visual: $(OBJ_VIS)
	g++ $(OBJ_VIS) $(OPTIONS) $(LIBS) -o $(TARGET_VIS)

$(OBJECT_VIS): $(SRC_VIS)


	
